package com.develop.basicandroid.movieapp3.models


data class Movie(
    val id: String,
    val actors: String,
    val awards: String,
    val country: String,
    val director: String,
    val genre: String,
    val images: List<String>,
    val language: String,
    val metascore: String,
    val plot: String,
    val poster: String,
    val rated: String,
    val released: String,
    val response: String,
    val runtime: String,
    val title: String,
    val type: String,
    val writer: String,
    val year: String,
    val imdbID: String,
    val imdbRating: String,
    val imdbVotes: String
)

fun getMovies(): List<Movie> {
    val movieList: List<Movie> = listOf(
        Movie(
            title = "Avatar",
            year = "2009",
            rated = "PG-13",
            released = "18 Dec 2009",
            runtime = "162 min",
            genre = "Action, Adventure, Fantasy",
            director = "James Cameron",
            writer = "James Cameron",
            actors = "Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang",
            plot = "A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
            language = "English, Spanish",
            country = "USA, UK",
            awards = "Won 3 Oscars. Another 80 wins & 121 nominations.",
            poster = "http://ia.media-imdb.com/images/M/MV5BMTYwOTEwNjAzMl5BMl5BanBnXkFtZTcwODc5MTUwMw@@._V1_SX300.jpg",
            metascore = "83",
            imdbRating = "7.9",
            imdbVotes = "890,617",
            imdbID = "tt0499549",
            type = "movie",
            response = "True",
            images = listOf(
                "https://www.dreamogram.com/wp-content/uploads/2018/12/043_dreamogram-iconisus-key-art-movie-poster-avatar-2_vertical-cover.jpg",
                "https://images-na.ssl-images-amazon.com/images/M/MV5BNzM2MDk3MTcyMV5BMl5BanBnXkFtZTcwNjg0MTUzNA@@._V1_SX1777_CR0,0,1777,999_AL_.jpg"
            ),
            id = "1"
        ),
        Movie(
            title = "Inception",
            year = "2010",
            rated = "PG-13",
            released = "16 Jul 2010",
            runtime = "148 min",
            genre = "Action, Adventure, Sci-Fi",
            director = "Christopher Nolan",
            writer = "Christopher Nolan",
            actors = "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page",
            plot = "A thief who enters the dreams of others to steal secrets from their subconscious is given the inverse task of planting an idea into the mind of a CEO.",
            language = "English, Japanese, French",
            country = "USA, UK",
            awards = "Won 4 Oscars. Another 143 wins & 198 nominations.",
            poster = "http://ia.media-imdb.com/images/M/MV5BMjE0NjkwNzg5OF5BMl5BanBnXkFtZTcwNTY0Mjg0Mw@@._V1_SX300.jpg",
            metascore = "74",
            imdbRating = "8.8",
            imdbVotes = "2,000,000",
            imdbID = "tt1375666",
            type = "movie",
            response = "True",
            images = listOf(
                "https://m.media-amazon.com/images/M/MV5BMzA3NDg5MzQ5NV5BMl5BanBnXkFtZTcwMDg0MTUzNA@@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
                "https://m.media-amazon.com/images/M/MV5BMTY2ODQ3NjMyMl5BMl5BanBnXkFtZTcwODg0MTUzNA@@._V1_SX1500_CR0,0,1500,999_AL_.jpg"
            ),
            id = "2"
        ),
        Movie(
            title = "The Dark Knight",
            year = "2008",
            rated = "PG-13",
            released = "18 Jul 2008",
            runtime = "152 min",
            genre = "Action, Crime, Drama",
            director = "Christopher Nolan",
            writer = "Jonathan Nolan, Christopher Nolan",
            actors = "Christian Bale, Heath Ledger, Aaron Eckhart",
            plot = "When the menace known as The Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.",
            language = "English, Mandarin",
            country = "USA, UK",
            awards = "Won 2 Oscars. Another 146 wins & 142 nominations.",
            poster = "http://ia.media-imdb.com/images/M/MV5BMTY5MTU2ODQzM15BMl5BanBnXkFtZTcwMDE5MTMyMw@@._V1_SX300.jpg",
            metascore = "84",
            imdbRating = "9.0",
            imdbVotes = "2,100,000",
            imdbID = "tt0468569",
            type = "movie",
            response = "True",
            images = listOf(
                "https://images-na.ssl-images-amazon.com/images/M/MV5BMTYzNzYwNzg1M15BMl5BanBnXkFtZTcwNTAzOTYyMQ@@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
                "https://images-na.ssl-images-amazon.com/images/M/MV5BMTYzNjkwNzE2M15BMl5BanBnXkFtZTcwNjA1NzU1NA@@._V1_SX1777_CR0,0,1777,999_AL_.jpg"
            ),
            id = "3"
        ),
        Movie(
            title = "The Matrix",
            year = "1999",
            rated = "R",
            released = "31 Mar 1999",
            runtime = "136 min",
            genre = "Action, Sci-Fi",
            director = "The Wachowskis",
            writer = "The Wachowskis",
            actors = "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
            plot = "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
            language = "English",
            country = "USA",
            awards = "Won 4 Oscars. Another 34 wins & 51 nominations.",
            poster = "http://ia.media-imdb.com/images/M/MV5BMTk5Nzc4Nzk4OV5BMl5BanBnXkFtZTcwNTYyODgyMw@@._V1_SX300.jpg",
            metascore = "73",
            imdbRating = "8.7",
            imdbVotes = "1,200,000",
            imdbID = "tt0133093",
            type = "movie",
            response = "True",
            images = listOf(
                "https://m.media-amazon.com/images/M/MV5BYjVjNmZmZTQtM2Y0ZC00ZmMwLTgxMGItNGE3ZjIzODdjNzI5XkEyXkFqcGdeQXNrX2hhZGZjL2NpZ2NlY2tvdy1idXluZXMtZGVjaXBlcy1sb3dfZWFzdC1mZXJpLWludGFjdC5wbmc@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
                "https://m.media-amazon.com/images/M/MV5BNzExMzI1MDM2NF5BMl5BanBnXkFtZTcwMjgyMDk0NA@@._V1_SX1500_CR0,0,1500,999_AL_.jpg"
            ),
            id = "4"
        ),
        Movie(
            title = "Titanic",
            year = "1997",
            rated = "PG-13",
            released = "19 Dec 1997",
            runtime = "195 min",
            genre = "Drama, Romance",
            director = "James Cameron",
            writer = "James Cameron",
            actors = "Leonardo DiCaprio, Kate Winslet, Billy Zane",
            plot = "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
            language = "English, Italian, Latin",
            country = "USA",
            awards = "Won 11 Oscars. Another 113 wins & 83 nominations.",
            poster = "http://ia.media-imdb.com/images/M/MV5BMTk5MzM0MDMwNF5BMl5BanBnXkFtZTcwNzI5MTg4MQ@@._V1_SX300.jpg",
            metascore = "75",
            imdbRating = "7.8",
            imdbVotes = "1,600,000",
            imdbID = "tt0120338",
            type = "movie",
            response = "True",
            images = listOf(
                "https://m.media-amazon.com/images/M/MV5BMjEyOTkwMjEyOF5BMl5BanBnXkFtZTcwNTczMDYzOQ@@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
                "https://m.media-amazon.com/images/M/MV5BMTk4NzA2MTk4MF5BMl5BanBnXkFtZTcwNTI3NzMwOQ@@._V1_SX1777_CR0,0,1777,999_AL_.jpg"
            ),
            id = "5"
        ),
        Movie(
            title = "The Lion King",
            year = "1994",
            rated = "G",
            released = "24 Jun 1994",
            runtime = "88 min",
            genre = "Animation, Adventure, Drama",
            director = "Roger Allers, Rob Minkoff",
            writer = "Irene Mecchi, Jonathan Roberts, Linda Woolverton",
            actors = "Matthew Broderick, Jeremy Irons, James Earl Jones",
            plot = "Lion prince Simba and his father are targeted by his evil uncle, who wants to rule the kingdom.",
            language = "English",
            country = "USA",
            awards = "Won 2 Oscars. Another 33 wins & 41 nominations.",
            poster = "http://ia.media-imdb.com/images/M/MV5BMjExNzc3Nzg2OF5BMl5BanBnXkFtZTcwMTgwNTg5Mw@@._V1_SX300.jpg",
            metascore = "85",
            imdbRating = "8.5",
            imdbVotes = "1,200,000",
            imdbID = "tt0110357",
            type = "movie",
            response = "True",
            images = listOf(
                "https://m.media-amazon.com/images/M/MV5BMjI2NjA2NjM2M15BMl5BanBnXkFtZTcwMDg4MTMyNA@@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
                "https://m.media-amazon.com/images/M/MV5BMTYwMzg2MTM4MF5BMl5BanBnXkFtZTcwNjg3MzY5Mg@@._V1_SX1777_CR0,0,1777,999_AL_.jpg"
            ),
            id = "6"
        ),
        Movie(
            title = "The Shawshank Redemption",
            year = "1994",
            rated = "R",
            released = "14 Oct 1994",
            runtime = "142 min",
            genre = "Drama",
            director = "Frank Darabont",
            writer = "Stephen King (short story), Frank Darabont",
            actors = "Tim Robbins, Morgan Freeman, Bob Gunton",
            plot = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
            language = "English",
            country = "USA",
            awards = "Nominated for 7 Oscars. Another 21 wins & 38 nominations.",
            poster = "http://ia.media-imdb.com/images/M/MV5BODc5ZmViZjUtNTdhNy00YjgyLWIwZGQtN2ExMzk0ZThhMGUyXkEyXkFqcGdeQXNrX2hhZGZjL2NpZ2NlY2tvdy1idXluZXMtZGVjaXBlcy1sb3dfZWFzdC1mZXJpLWludGFjdC5wbmc@._V1_SX300.jpg",
            metascore = "80",
            imdbRating = "9.3",
            imdbVotes = "2,400,000",
            imdbID = "tt0111161",
            type = "movie",
            response = "True",
            images = listOf(
                "https://m.media-amazon.com/images/M/MV5BMTc3Mzc1Nzc1OV5BMl5BanBnXkFtZTcwMzU5NjM1OA@@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
                "https://m.media-amazon.com/images/M/MV5BMTU4NzE2Mjg3OV5BMl5BanBnXkFtZTcwNjE4ODkwOQ@@._V1_SX1777_CR0,0,1777,999_AL_.jpg"
            ),
            id = "7"
        ),
        Movie(
            title = "Forrest Gump",
            year = "1994",
            rated = "PG-13",
            released = "6 Jul 1994",
            runtime = "142 min",
            genre = "Drama, Romance",
            director = "Robert Zemeckis",
            writer = "Winston Groom (novel), Eric Roth",
            actors = "Tom Hanks, Robin Wright, Gary Sinise",
            plot = "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an extraordinary history.",
            language = "English",
            country = "USA",
            awards = "Won 6 Oscars. Another 45 wins & 61 nominations.",
            poster = "http://ia.media-imdb.com/images/M/MV5BMjA5NzMxMDgxNF5BMl5BanBnXkFtZTcwNzI4MDcwMw@@._V1_SX300.jpg",
            metascore = "82",
            imdbRating = "8.8",
            imdbVotes = "2,000,000",
            imdbID = "tt0109830",
            type = "movie",
            response = "True",
            images = listOf(
                "https://m.media-amazon.com/images/M/MV5BMTYyMTQzNjY3M15BMl5BanBnXkFtZTcwNjc5NzQ4Mg@@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
                "https://m.media-amazon.com/images/M/MV5BMTYzNjgwNzg0M15BMl5BanBnXkFtZTcwMTg3MzE3OQ@@._V1_SX1777_CR0,0,1777,999_AL_.jpg"
            ),
            id = "8"
        ),
        Movie(
            title = "Pulp Fiction",
            year = "1994",
            rated = "R",
            released = "14 Oct 1994",
            runtime = "154 min",
            genre = "Crime, Drama",
            director = "Quentin Tarantino",
            writer = "Quentin Tarantino",
            actors = "John Travolta, Uma Thurman, Samuel L. Jackson",
            plot = "The lives of two mob hitmen, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
            language = "English",
            country = "USA",
            awards = "Won 1 Oscar. Another 69 wins & 76 nominations.",
            poster = "http://ia.media-imdb.com/images/M/MV5BMjI5NjYxODkzMV5BMl5BanBnXkFtZTcwNTI0MDMwMg@@._V1_SX300.jpg",
            metascore = "94",
            imdbRating = "8.9",
            imdbVotes = "1,600,000",
            imdbID = "tt0110912",
            type = "movie",
            response = "True",
            images = listOf(
                "https://m.media-amazon.com/images/M/MV5BMTYwMzQzMjczNV5BMl5BanBnXkFtZTcwODc0OTIzOQ@@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
                "https://m.media-amazon.com/images/M/MV5BMTY1NzkxNTExM15BMl5BanBnXkFtZTcwNjg2MzM2Mg@@._V1_SX1777_CR0,0,1777,999_AL_.jpg"
            ),
            id = "9"
        ),
        Movie(
            title = "The Godfather",
            year = "1972",
            rated = "R",
            released = "24 Mar 1972",
            runtime = "175 min",
            genre = "Crime, Drama",
            director = "Francis Ford Coppola",
            writer = "Mario Puzo (novel), Francis Ford Coppola",
            actors = "Marlon Brando, Al Pacino, James Caan",
            plot = "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
            language = "English, Italian, Latin",
            country = "USA",
            awards = "Won 3 Oscars. Another 31 wins & 31 nominations.",
            poster = "http://ia.media-imdb.com/images/M/MV5BMjM3NDk0NzkxNF5BMl5BanBnXkFtZTcwMzc4ODQwMw@@._V1_SX300.jpg",
            metascore = "100",
            imdbRating = "9.2",
            imdbVotes = "1,500,000",
            imdbID = "tt0068646",
            type = "movie",
            response = "True",
            images = listOf(
                "https://m.media-amazon.com/images/M/MV5BMjA5MjA5MjExMF5BMl5BanBnXkFtZTcwNTkwNjc4MQ@@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
                "https://m.media-amazon.com/images/M/MV5BMTc5NzMyNzQ5M15BMl5BanBnXkFtZTcwNTMwMzg3Mg@@._V1_SX1500_CR0,0,1500,999_AL_.jpg"
            ),
            id = "10"
        )
    )
    return movieList
}

fun getMovieById(id : String) : Movie {
    return getMovies().first { movie ->
        movie.id == id
    }
}
